### ISSUE TITLE
Data model changes and recommendations

### ISSUE THREAD

**Issue by arwhyte** [lopiyuquita/si664finalproject#1]
### Naming conventions
Follow Simon Holywell's https://www.sqlstyle.guide/ (introduced early in the course).
* Change all `id` property names such that each is suffixed with `_id` (e.g., `idcountry` to `country_id`)
* Use singular rather than plural form for entity names (e.g., `wines` to `wine`, `wineries` to `winery`, `varieties` to `variety`)
* Change `idtitle` to `wine_id`.
* On Foreign keys, drop table name prefix (e.g., countries_idcountry -> `country_id`)

### Associative/Junction tables
* Change `tasters_has_wines` to `wine_taster`.
* Change `varieties_has_wineries` to `winery_variety`
* Move `wine.points` to `wine_taster` table (taster awards the wine with points, yeah? https://www.winespectator.com/display/show/id/scoring-scale)

### Consider slimming down the data model
I recommend dropping the following tables from the model:
* `region1` (plus FK in `wine`)
* `region2` (plus FK in `wine`)
* `region1_has_varieties` (renamed as `region1_variety`)
* `varieties_has_region2` (renamed as `region2_variety`)

While the added regional highlights are interesting, adding the tables will require time and energy that I consider better spent elsewhere.

**Comment by lopiyuquita** [comment]
See my latest commit:
1. Naming conventions (Done)
2. Associative/Junction tables (Done)
3. Data model: I will keep the four tables.

**Comment by arwhyte** [comment]
One tiny error.  The `pints` field should be `points`.  Fix the error, update the model image, and then you can close the issue.

**Comment by lopiyuquita** [comment]
The error fixed.
